//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLIENTE_PRUEBA.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlpinismoBE", Namespace="http://schemas.datacontract.org/2004/07/Alpinismo.BD")]
    [System.SerializableAttribute()]
    public partial class AlpinismoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Deporte {
            get {
                return this.DeporteField;
            }
            set {
                if ((object.ReferenceEquals(this.DeporteField, value) != true)) {
                    this.DeporteField = value;
                    this.RaisePropertyChanged("Deporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Horario {
            get {
                return this.HorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HorarioField, value) != true)) {
                    this.HorarioField = value;
                    this.RaisePropertyChanged("Horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAlpinismoServices")]
    public interface IAlpinismoServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlpinismoServices/DoWork", ReplyAction="http://tempuri.org/IAlpinismoServices/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlpinismoServices/insertar", ReplyAction="http://tempuri.org/IAlpinismoServices/insertarResponse")]
        string insertar(CLIENTE_PRUEBA.ServiceReference1.AlpinismoBE hboe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlpinismoServices/listar", ReplyAction="http://tempuri.org/IAlpinismoServices/listarResponse")]
        System.Data.DataSet listar();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlpinismoServicesChannel : CLIENTE_PRUEBA.ServiceReference1.IAlpinismoServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlpinismoServicesClient : System.ServiceModel.ClientBase<CLIENTE_PRUEBA.ServiceReference1.IAlpinismoServices>, CLIENTE_PRUEBA.ServiceReference1.IAlpinismoServices {
        
        public AlpinismoServicesClient() {
        }
        
        public AlpinismoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlpinismoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlpinismoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlpinismoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public string insertar(CLIENTE_PRUEBA.ServiceReference1.AlpinismoBE hboe) {
            return base.Channel.insertar(hboe);
        }
        
        public System.Data.DataSet listar() {
            return base.Channel.listar();
        }
    }
}
